<?php

namespace Database\Seeders;

use App\Models\Menu;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // ── Users ──
        User::create([
            'name'     => 'Owner Seoul Serenity',
            'email'    => 'owner@seoulserenity.id',
            'phone'    => '081200000001',
            'password' => Hash::make('password'),
            'role'     => 'owner',
        ]);

        User::create([
            'name'     => 'Staff Dapur',
            'email'    => 'staff01@seoulserenity.id',
            'phone'    => '081200000002',
            'password' => Hash::make('password'),
            'role'     => 'staff',
        ]);

        User::create([
            'name'     => 'Budi Santoso',
            'email'    => 'budi@email.com',
            'phone'    => '081234567890',
            'password' => Hash::make('password'),
            'role'     => 'customer',
        ]);

        // ── MENU LENGKAP 40 ITEMS DENGAN NAMA FILE YANG BENAR ──
        $menus = [

            // ========== SUP & JJIGAE (7 menu) ==========
            [
                'name'         => 'Budae Jjigae',
                'name_ko'      => '부대찌개',
                'description'  => 'Army stew pedas dengan kimchi, sosis, baked bean, dan ramyeon',
                'category'     => 'Sup & Jjigae',
                'price'        => 45000,
                'emoji'        => '🍲',
                'image'        => '1778505953_Budae_Jigae___Salin.png',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Kimchi Jjigae',
                'name_ko'      => '김치찌개',
                'description'  => 'Sup kimchi pedas dengan tofu, pork belly, dan daun bawang',
                'category'     => 'Sup & Jjigae',
                'price'        => 32000,
                'emoji'        => '🥘',
                'image'        => 'kimchi Jjigae.jpg',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Doenjang Jjigae',
                'name_ko'      => '된장찌개',
                'description'  => 'Sup doenjang gurih dengan sayuran, tofu, dan jamur',
                'category'     => 'Sup & Jjigae',
                'price'        => 30000,
                'emoji'        => '🍲',
                'image'        => '1778506072_Doejang_Jigae.webp',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Sundubu Jjigae',
                'name_ko'      => '순두부찌개',
                'description'  => 'Sup tofu lembut pedas dengan seafood dan telur mentah',
                'category'     => 'Sup & Jjigae',
                'price'        => 35000,
                'emoji'        => '🥣',
                'image'        => '1778504519_sundubu.webp',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Galbitang',
                'name_ko'      => '갈비탕',
                'description'  => 'Sup iga sapi bening gurih dengan daun bawang dan lobak',
                'category'     => 'Sup & Jjigae',
                'price'        => 42000,
                'emoji'        => '🍖',
                'image'        => '1778504467_galbitang.webp',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Yukgaejang',
                'name_ko'      => '육개장',
                'description'  => 'Sup daging sapi pedas dengan daun bawang dan telur',
                'category'     => 'Sup & Jjigae',
                'price'        => 38000,
                'emoji'        => '🥬',
                'image'        => '1778504532_yukgaejang.jpg',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Samgyetang',
                'name_ko'      => '삼계탕',
                'description'  => 'Sup ayam kampung dengan ginseng, beras ketan, dan kurma',
                'category'     => 'Sup & Jjigae',
                'price'        => 55000,
                'emoji'        => '🍗',
                'image'        => '1778504500_samgyetang.jpeg',
                'bg_class'     => 'bg-sup',
                'is_available' => true,
                'is_featured'  => false,
            ],

            // ========== BBQ & GRILL (7 menu) ==========
            [
                'name'         => 'Galbi-gui',
                'name_ko'      => '갈비구이',
                'description'  => 'Iga sapi panggang dengan saus soy-pear marinade',
                'category'     => 'BBQ & Grill',
                'price'        => 78000,
                'emoji'        => '🥩',
                'image'        => '1778313677_galbi gui.jpg',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Samgyeopsal',
                'name_ko'      => '삼겹살',
                'description'  => 'Pork belly panggang dengan ssamjang, bawang putih, dan selada',
                'category'     => 'BBQ & Grill',
                'price'        => 65000,
                'emoji'        => '🥓',
                'image'        => '1778313726_samgyeopsal.jpeg',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Dakgalbi',
                'name_ko'      => '닭갈비',
                'description'  => 'Ayam pedas panggang dengan saus gochujang dan kol',
                'category'     => 'BBQ & Grill',
                'price'        => 45000,
                'emoji'        => '🍗',
                'image'        => '1778506057_Dakgalbi.png',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Bulgogi',
                'name_ko'      => '불고기',
                'description'  => 'Daging sapi manis panggang dengan bawang bombay dan jamur',
                'category'     => 'BBQ & Grill',
                'price'        => 52000,
                'emoji'        => '🍖',
                'image'        => '1778506004_Bulgogi___Salin.png',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Nakji-bokkeum',
                'name_ko'      => '낙지볶음',
                'description'  => 'Sauté gurita pedas dengan gochujang dan sayuran',
                'category'     => 'BBQ & Grill',
                'price'        => 48000,
                'emoji'        => '🐙',
                'image'        => '1778313709_nakji bokkeum.jpg',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Eomuk-gui',
                'name_ko'      => '어묵구이',
                'description'  => 'Fish cake panggang dengan saus pedas manis',
                'category'     => 'BBQ & Grill',
                'price'        => 18000,
                'emoji'        => '🍢',
                'image'        => '1778506524_eomok_gui.JPG',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Godeungeo-gui',
                'name_ko'      => '고등어구이',
                'description'  => 'Ikan mackerel panggang dengan garam dan minyak wijen',
                'category'     => 'BBQ & Grill',
                'price'        => 35000,
                'emoji'        => '🐟',
                'image'        => '1778313696_godeungeo gui.webp',
                'bg_class'     => 'bg-bbq',
                'is_available' => true,
                'is_featured'  => false,
            ],

            // ========== NASI & BENTO (7 menu) ==========
            [
                'name'         => 'Bibimbap',
                'name_ko'      => '비빔밥',
                'description'  => 'Nasi campur dengan sayuran, daging sapi, telur, dan gochujang',
                'category'     => 'Nasi & Bento',
                'price'        => 38000,
                'emoji'        => '🍚',
                'image'        => '1778505969_Bibimbap___Salin.png',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Kimchi Bokkeumbap',
                'name_ko'      => '김치볶음밥',
                'description'  => 'Nasi goreng kimchi dengan pork belly dan telur mata sapi',
                'category'     => 'Nasi & Bento',
                'price'        => 28000,
                'emoji'        => '🍚',
                'image'        => '1778314264_kimchi bokkeumbap.jpg',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Kimbab',
                'name_ko'      => '김밥',
                'description'  => 'Nasi gulung dengan sayuran, daging sapi, dan telur',
                'category'     => 'Nasi & Bento',
                'price'        => 25000,
                'emoji'        => '🍙',
                'image'        => '1778314249_kimbab.jpg',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Ojingeo Deopbap',
                'name_ko'      => '오징어덮밥',
                'description'  => 'Nasi dengan cumi pedas dan sayuran di atasnya',
                'category'     => 'Nasi & Bento',
                'price'        => 32000,
                'emoji'        => '🦑',
                'image'        => '1778314345_ojingo.jpeg',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Jeyuk Bokkeum',
                'name_ko'      => '제육볶음',
                'description'  => 'Nasi dengan tumis pork pedas dan gochujang',
                'category'     => 'Nasi & Bento',
                'price'        => 34000,
                'emoji'        => '🥘',
                'image'        => '1778314234_Jeyuk-bokkeum.webp',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Gyeran Bap',
                'name_ko'      => '계란밥',
                'description'  => 'Nasi dengan telur mentah, kecap asin, dan minyak wijen',
                'category'     => 'Nasi & Bento',
                'price'        => 15000,
                'emoji'        => '🍳',
                'image'        => '1778314216_gyeran-bap.jpg',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Dolsot Bibimbap',
                'name_ko'      => '돌솥비빔밥',
                'description'  => 'Bibimbap dalam mangkuk batu panas dengan nasi krispi',
                'category'     => 'Nasi & Bento',
                'price'        => 45000,
                'emoji'        => '🏺',
                'image'        => '1778506094_Dolsot_Bibimbap.jpg',
                'bg_class'     => 'bg-nasi',
                'is_available' => true,
                'is_featured'  => true,
            ],

            // ========== MIE & RAMYEON (7 menu) ==========
            [
                'name'         => 'Jjamppong',
                'name_ko'      => '짬뽕',
                'description'  => 'Mie seafood pedas dengan kuah merah kental',
                'category'     => 'Mie & Ramyeon',
                'price'        => 38000,
                'emoji'        => '🍜',
                'image'        => '1778313798_Jjamppong.webp',
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Jjajangmyeon',
                'name_ko'      => '짜장면',
                'description'  => 'Mie dengan saus black bean kental dan daging babi',
                'category'     => 'Mie & Ramyeon',
                'price'        => 32000,
                'emoji'        => '🍜',
                'image'        => '1778313754_jjajangmyeon.jpg',
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Ramyeon',
                'name_ko'      => '라면',
                'description'  => 'Mie instan Korea dengan topping kimchi dan telur',
                'category'     => 'Mie & Ramyeon',
                'price'        => 18000,
                'emoji'        => '🍲',
                'image'        => null,
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Naengmyeon',
                'name_ko'      => '냉면',
                'description'  => 'Mie dingin kuah es dengan daging sapi, timun, dan lobak',
                'category'     => 'Mie & Ramyeon',
                'price'        => 30000,
                'emoji'        => '🥶',
                'image'        => '1778313839_naengmyeon.jpg',
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Kalguksu',
                'name_ko'      => '칼국수',
                'description'  => 'Mie potong tangan dengan kuah kaldu ayam gurih',
                'category'     => 'Mie & Ramyeon',
                'price'        => 28000,
                'emoji'        => '🍜',
                'image'        => '1778313812_kalguksu.jpg',
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Bibim Guksu',
                'name_ko'      => '비빔국수',
                'description'  => 'Mie dingin pedas dengan saus gochujang dan sayuran',
                'category'     => 'Mie & Ramyeon',
                'price'        => 22000,
                'emoji'        => '🍝',
                'image'        => '1778505615_Bibim_Guksu___Salin.png',
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Mul Naengmyeon',
                'name_ko'      => '물냉면',
                'description'  => 'Mie dingin kuah bening dengan es batu dan cuka',
                'category'     => 'Mie & Ramyeon',
                'price'        => 28000,
                'emoji'        => '🧊',
                'image'        => '1778313826_mul naengmyeon.jpg',
                'bg_class'     => 'bg-mie',
                'is_available' => true,
                'is_featured'  => false,
            ],

            // ========== MINUMAN (8 menu) ==========
            [
                'name'         => 'Sikhye',
                'name_ko'      => '식혜',
                'description'  => 'Minuman manis tradisional Korea dari beras fermentasi',
                'category'     => 'Minuman',
                'price'        => 15000,
                'emoji'        => '🍶',
                'image'        => '1778314163_sikhye.jpg',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Korean Yogurt Soda',
                'name_ko'      => '요구르트',
                'description'  => 'Yogurt soda segar dengan rasa vanilla',
                'category'     => 'Minuman',
                'price'        => 12000,
                'emoji'        => '🥤',
                'image'        => '1778314070_korean yogurt soda.jpg',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Korean Barley Tea',
                'name_ko'      => '보리차',
                'description'  => 'Teh jelai Korea (bisa panas atau dingin)',
                'category'     => 'Minuman',
                'price'        => 8000,
                'emoji'        => '☕',
                'image'        => '1778313936_korean barley tea.jpg',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Citron Tea',
                'name_ko'      => '유자차',
                'description'  => 'Teh yuzu hangat dengan madu dan lemon',
                'category'     => 'Minuman',
                'price'        => 10000,
                'emoji'        => '🍵',
                'image'        => '1778505984_Citron_Tea___Salin.png',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Banana Milk',
                'name_ko'      => '바나나우유',
                'description'  => 'Susu pisang manis khas Korea',
                'category'     => 'Minuman',
                'price'        => 12000,
                'emoji'        => '🥛',
                'image'        => '1778505669_Banana_Milk___Salin.png',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Rice Drink',
                'name_ko'      => '미숫가루',
                'description'  => 'Minuman beras Korea dengan kacang-kacangan',
                'category'     => 'Minuman',
                'price'        => 10000,
                'emoji'        => '🧃',
                'image'        => '1778314148_RiceDrink.jpeg',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Korean Bubble Tea',
                'name_ko'      => '버블티',
                'description'  => 'Bubble tea dengan pilihan rasa taro, matcha, atau red bean',
                'category'     => 'Minuman',
                'price'        => 18000,
                'emoji'        => '🧋',
                'image'        => '1778314021_korean bubble tea.jpg',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Plum Ade',
                'name_ko'      => '매실에이드',
                'description'  => 'Minuman plum segar dengan soda dan es batu',
                'category'     => 'Minuman',
                'price'        => 16000,
                'emoji'        => '🍹',
                'image'        => '1778314098_PlumAde.jpeg',
                'bg_class'     => 'bg-minuman',
                'is_available' => true,
                'is_featured'  => false,
            ],

            // ========== SNACK (4 menu) ==========
            [
                'name'         => 'Tteokbokki',
                'name_ko'      => '떡볶이',
                'description'  => 'Kue beras pedas manis dengan saus gochujang dan fish cake',
                'category'     => 'Snack',
                'price'        => 22000,
                'emoji'        => '🍡',
                'image'        => '1778314410_tteokbokki.jpeg',
                'bg_class'     => 'bg-snack',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Japchae',
                'name_ko'      => '잡채',
                'description'  => 'Bihun glass noodle dengan sayuran dan daging sapi',
                'category'     => 'Snack',
                'price'        => 32000,
                'emoji'        => '🥗',
                'image'        => '1778314366_japchae.webp',
                'bg_class'     => 'bg-snack',
                'is_available' => true,
                'is_featured'  => true,
            ],
            [
                'name'         => 'Pajeon',
                'name_ko'      => '파전',
                'description'  => 'Pancake daun bawang renyah dengan seafood',
                'category'     => 'Snack',
                'price'        => 25000,
                'emoji'        => '🧇',
                'image'        => '1778314395_pajeon.webp',
                'bg_class'     => 'bg-snack',
                'is_available' => true,
                'is_featured'  => false,
            ],
            [
                'name'         => 'Mandu',
                'name_ko'      => '만두',
                'description'  => 'Pangsit Korea dengan isian daging dan sayuran',
                'category'     => 'Snack',
                'price'        => 18000,
                'emoji'        => '🥟',
                'image'        => '1778314380_mandu.jpg',
                'bg_class'     => 'bg-snack',
                'is_available' => true,
                'is_featured'  => false,
            ],
        ];

        foreach ($menus as $menu) {
            Menu::create($menu);
        }

        $this->command->info('✅ Database seeded successfully!');
        $this->command->info('📊 Total users: ' . User::count());
        $this->command->info('🍽️ Total menus: ' . Menu::count());

        $categories = Menu::select('category')->distinct()->get();
        $this->command->info('📂 Categories:');
        foreach ($categories as $cat) {
            $count = Menu::where('category', $cat->category)->count();
            $this->command->info("   - {$cat->category}: {$count} items");
        }
    }
}